In [2]:
# import des librairies
from pathlib import Path
import zipfile

import pandas as pd
import soccerdata as sd

In [3]:
# création des dossiers de données

RAW_DIR = Path("../data/raw")

KAGGLE_DIR = RAW_DIR / "kaggle"
SOCCER_DIR = RAW_DIR / "soccerdata"

KAGGLE_DIR.mkdir(parents=True, exist_ok=True)
SOCCER_DIR.mkdir(parents=True, exist_ok=True)

print("Dossiers créés.")

Dossiers créés.

In [4]:
# téléchargement du dataset FIFA World Cup depuis Kaggle

import os

dataset = "piterfm/fifa-football-world-cup"

os.system(
    f"kaggle datasets download -d {dataset} -p {KAGGLE_DIR}"
)

0

In [5]:
# extraction du fichier zip

zip_file = list(KAGGLE_DIR.glob("*.zip"))[0]

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall(KAGGLE_DIR)

print("Dataset Kaggle extrait.")

Dataset Kaggle extrait.

In [6]:
# voir les fichiers extraits

list(KAGGLE_DIR.glob("*"))

[WindowsPath('../data/raw/kaggle/fifa-football-world-cup.zip'),
 WindowsPath('../data/raw/kaggle/fifa_ranking_2022-10-06.csv'),
 WindowsPath('../data/raw/kaggle/fifa_ranking_2026-06-08.csv'),
 WindowsPath('../data/raw/kaggle/matches_1930_2022.csv'),
 WindowsPath('../data/raw/kaggle/schedule_2026.csv'),
 WindowsPath('../data/raw/kaggle/world_cup.csv')]

In [8]:
# connexion a la base de données SoccerData

fb = sd.FBref(
    leagues="INT-World Cup",
    seasons=[2014, 2018, 2022]
)

[07/02/26 10:19:58] INFO     Saving cached data to C:\Users\lea\soccerdata\data\FBref                ]8;id=11278284;file://C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=11278285;file://C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\soccerdata\_common.py#250\250]8;;\

Warning: uc_driver not found. Getting it now:

*** chromedriver to download = 149.0.7827.155 (Previous Version)

Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/149.0.7827.155/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Unzip Complete!

The file [uc_driver.exe] was saved to:
C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\seleniumbase\drivers\
uc_driver.exe

Making [uc_driver.exe 149.0.7827.155] executable ...
[uc_driver.exe 149.0.7827.155] is now ready for use!


*** chromedriver to download = 149.0.7827.155 (Previous Version)

Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/149.0.7827.155/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Unzip Complete!

The file [chromedriver.exe] was saved to:
C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\seleniumbase\drivers\
chromedriver.exe

Making [chromedriver.exe 149.0.7827.155] executable ...
[chromedriver.exe 149.0.7827.155] is now ready for use!

In [9]:
# Calendrier des matchs 

schedule = fb.read_schedule()

schedule.to_csv(
    SOCCER_DIR / "schedule.csv",
    index=False
)

schedule.head()

[07/02/26 10:20:29] WARNING  C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3. warnings.py:110
                             11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\soc
                             cerdata\fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

                                                         round  week  day  \
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia     Group stage     1  Thu
                     2014-06-13 Chile-Australia    Group stage     1  Fri
                     2014-06-13 Mexico-Cameroon    Group stage     1  Fri
                     2014-06-13 Spain-Netherlands  Group stage     1  Fri
                     2014-06-14 Colombia-Greece    Group stage     1  Sat

                                                        date           time  \
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia    2014-06-12  17:00 (22:00)
                     2014-06-13 Chile-Australia   2014-06-13  18:00 (00:00)
                     2014-06-13 Mexico-Cameroon   2014-06-13  13:00 (18:00)
                     2014-06-13 Spain-Netherlands 2014-06-13  16:00 (21:00)
                     2014-06-14 Colombia-Greece   2014-06-14  13:00 (18:00)

                                                  home_team score  \
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia       Brazil   3–1
                     2014-06-13 Chile-Australia       Chile   3–1
                     2014-06-13 Mexico-Cameroon      Mexico   1–0
                     2014-06-13 Spain-Netherlands     Spain   1–5
                     2014-06-14 Colombia-Greece    Colombia   3–0

                                                     away_team  attendance  \
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia         Croatia       62103
                     2014-06-13 Chile-Australia      Australia       40275
                     2014-06-13 Mexico-Cameroon       Cameroon       39216
                     2014-06-13 Spain-Netherlands  Netherlands       48173
                     2014-06-14 Colombia-Greece         Greece       57174

                                                                                               venue  \
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia                      Arena Corinthians (Neutral Site)
                     2014-06-13 Chile-Australia                        Arena Pantanal (Neutral Site)
                     2014-06-13 Mexico-Cameroon                       Arena das Dunas (Neutral Site)
                     2014-06-13 Spain-Netherlands           Itaipava Arena Fonte Nova (Neutral Site)
                     2014-06-14 Colombia-Greece    Estádio Governador Magalhães Pinto (Neutral Site)

                                                            referee  \
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia     Yuichi Nishimura
                     2014-06-13 Chile-Australia     Noumandiez Doué
                     2014-06-13 Mexico-Cameroon       Wilmar Roldán
                     2014-06-13 Spain-Netherlands    Nicola Rizzoli
                     2014-06-14 Colombia-Greece         Mark Geiger

                                                                                        match_report  \
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia     /en/matches/0a93d0e2/Brazil-Croatia-June-12-20...
                     2014-06-13 Chile-Australia    /en/matches/91edb9db/Chile-Australia-June-13-2...
                     2014-06-13 Mexico-Cameroon    /en/matches/1e731368/Mexico-Cameroon-June-13-2...
                     2014-06-13 Spain-Netherlands  /en/matches/df94a7ed/Spain-Netherlands-June-13...
                     2014-06-14 Colombia-Greece    /en/matches/2ed82ce3/Colombia-Greece-June-14-2...

                                                  notes   game_id
league        season game
INT-World Cup 2014   2014-06-12 Brazil-Croatia     <NA>  0a93d0e2
                     2014-06-13 Chile-Australia    <NA>  91edb9db
                     2014-06-13 Mexico-Cameroon    <NA>  1e731368
                     2014-06-13 Spain-Netherlands  <NA>  df94a7ed
                     2014-06-14 Colombia-Greece    <NA>  2ed82ce3

In [10]:
# statistiques des joueurs
players = fb.read_player_season_stats(
    stat_type="standard"
)

players.to_csv(
    SOCCER_DIR / "player_stats.csv",
    index=True
)

players.head()

[02/07/2026 10:25:17] WARNING  C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python. warnings.py:110
                               3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
                               \soccerdata\fbref.py:171: FutureWarning: The behavior of DataFrame
                               concatenation with empty or all-NA entries is deprecated. In a
                               future version, this will no longer exclude empty or all-NA columns
                               when determining the result dtypes. To retain the old behavior,
                               exclude the relevant entries before the concat operation.
                                 pd.concat(dfs)

[02/07/2026 10:25:57] WARNING  C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python. warnings.py:110
                               3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
                               \soccerdata\fbref.py:1119: UserWarning: Different columns found for
                               [['INT-World Cup' '2022']] and [['INT-World Cup' '2014']].

                               The following columns are missing in [['INT-World Cup' '2022']]:
                               (None, 'Club').

                               The following columns are missing in [['INT-World Cup' '2014']]: .

                               The columns of the dataframe with the most columns will be used.
                                 warnings.warn(

                      WARNING  C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python. warnings.py:110
                               3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
                               \soccerdata\fbref.py:1119: UserWarning: Different columns found for
                               [['INT-World Cup' '2022']] and [['INT-World Cup' '2018']].

                               The following columns are missing in [['INT-World Cup' '2022']]:
                               (None, 'Club').

                               The following columns are missing in [['INT-World Cup' '2018']]: .

                               The columns of the dataframe with the most columns will be used.
                                 warnings.warn(

                      WARNING  C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python. warnings.py:110
                               3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
                               \soccerdata\fbref.py:1172: FutureWarning: The behavior of DataFrame
                               concatenation with empty or all-NA entries is deprecated. In a
                               future version, this will no longer exclude empty or all-NA columns
                               when determining the result dtypes. To retain the old behavior,
                               exclude the relevant entries before the concat operation.
                                 return pd.concat(dfs)

                                                   nation    pos age  Club  \

league        season team    player
INT-World Cup 2014   Algeria Abdelmoumene Djabou  Algeria     MF  27  <NA>
                             Aïssa Mandi          Algeria     DF  22  <NA>
                             Carl Medjani         Algeria  DF,MF  29  <NA>
                             Djamel Mesbah        Algeria  DF,MF  29  <NA>
                             Essaïd Belkalem      Algeria     DF  25  <NA>

                                                 Playing Time                 \
                                                         born MP Starts  Min
league        season team    player
INT-World Cup 2014   Algeria Abdelmoumene Djabou         <NA>  3      2  169
                             Aïssa Mandi                 <NA>  3      3  300
                             Carl Medjani                <NA>  3      3  263
                             Djamel Mesbah               <NA>  2      2  180
                             Essaïd Belkalem             <NA>  3      2  212

                                                      Performance  ...       \
                                                  90s         Gls  ... G-PK
league        season team    player                                ...
INT-World Cup 2014   Algeria Abdelmoumene Djabou  1.9           2  ...    2
                             Aïssa Mandi          3.3           0  ...    0
                             Carl Medjani         2.9           0  ...    0
                             Djamel Mesbah        2.0           0  ...    0
                             Essaïd Belkalem      2.4           0  ...    0

                                                                     \
                                                 PK PKatt CrdY CrdR
league        season team    player
INT-World Cup 2014   Algeria Abdelmoumene Djabou  0     0    0    0
                             Aïssa Mandi          0     0    0    0
                             Carl Medjani         0     0    0    0
                             Djamel Mesbah        0     0    1    0
                             Essaïd Belkalem      0     0    0    0

                                                 Per 90 Minutes              \
                                                            Gls   Ast   G+A
league        season team    player
INT-World Cup 2014   Algeria Abdelmoumene Djabou           1.07  0.53   1.6
                             Aïssa Mandi                    0.0   0.0   0.0
                             Carl Medjani                   0.0  0.34  0.34
                             Djamel Mesbah                  0.0   0.0   0.0
                             Essaïd Belkalem                0.0   0.0   0.0


                                                  G-PK G+A-PK
league        season team    player
INT-World Cup 2014   Algeria Abdelmoumene Djabou  1.07    1.6
                             Aïssa Mandi           0.0    0.0
                             Carl Medjani          0.0   0.34
                             Djamel Mesbah         0.0    0.0
                             Essaïd Belkalem       0.0    0.0

[5 rows x 22 columns]

In [11]:
# statistiques offensives
shooting = fb.read_player_season_stats(
    stat_type="shooting"
)

shooting.to_csv(
    SOCCER_DIR / "player_shooting.csv"
)

[02/07/2026 10:30:06] WARNING  C:\Users\lea\AppData\Local\Packages\PythonSoftwareFoundation.Python. warnings.py:110
                               3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
                               \soccerdata\fbref.py:171: FutureWarning: The behavior of DataFrame
                               concatenation with empty or all-NA entries is deprecated. In a
                               future version, this will no longer exclude empty or all-NA columns
                               when determining the result dtypes. To retain the old behavior,
                               exclude the relevant entries before the concat operation.
                                 pd.concat(dfs)

In [ ]:
# statistiques des passes

passing = fb.read_player_season_stats(
    stat_type="passing"
)

passing.to_csv(
    SOCCER_DIR / "player_passing.csv"
)

In [ ]:
# statistiques des défenses
defense = fb.read_player_season_stats(
    stat_type="defense"
)

defense.to_csv(
    SOCCER_DIR / "player_defense.csv"
)

In [ ]:
# statistiques des possessions

possession = fb.read_player_season_stats(
    stat_type="possession"
)

possession.to_csv(
    SOCCER_DIR / "player_possession.csv"
)

In [ ]:
# statistiques des équipes

team_stats = fb.read_team_season_stats(
    stat_type="standard"
)

team_stats.to_csv(
    SOCCER_DIR / "team_stats.csv"
)

In [12]:
# test de lecture des fichiers CSV
for file in SOCCER_DIR.glob("*.csv"):
    print(file.name)

player_shooting.csv
player_stats.csv
schedule.csv